# Generated by Django 4.0.10 on 2023-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_character', models.CharField(max_length=255)),
                ('alt_character', models.CharField(max_length=255)),
            ],
        ),
    ]
