# Generated by Django 4.0.10 on 2023-05-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0004_alter_general_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('capsuleer_top', 'Can access capsuleer top statistics'), ('capsuleer_logi', 'Can access capsuleer logi statistics'), ('capsuleer_boosts', 'Can access capsuleer boosts statistics'), ('capsuleer_tackle', 'Can access capsuleer tackle statistics'), ('capsuleer_snowflakes', 'Can access capsuleer snowflakes statistics'), ('capsuleer_caps', 'Can access capsuleer caps statistics'), ('capsuleer_fax', 'Can access capsuleer fax statistics'), ('capsuleer_supers', 'Can access capsuleer supers statistics'), ('capsuleer_titans', 'Can access capsuleer titans statistics'), ('corporations_total', 'Can access corporations total statistics'), ('corporations_relative', 'Can access corporations relative statistics'))},
        ),
    ]
