# Generated by Django 4.0.10 on 2023-05-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0005_alter_general_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('capsuleer_top', 'Can access capsuleer top statistics'), ('capsuleer_logi', 'Can access capsuleer logi statistics'), ('capsuleer_boosts', 'Can access capsuleer boosts statistics'), ('capsuleer_tackle', 'Can access capsuleer tackle statistics'), ('capsuleer_snowflakes', 'Can access capsuleer snowflakes statistics'), ('capsuleer_caps', 'Can access capsuleer caps statistics'), ('capsuleer_fax', 'Can access capsuleer fax statistics'), ('capsuleer_supers', 'Can access capsuleer supers statistics'), ('capsuleer_titans', 'Can access capsuleer titans statistics'), ('corporations_total', 'Can access corporations total statistics'), ('corporations_relative', 'Can access corporations relative statistics'), ('corporations_logi', 'Can access corporations logi statistics'), ('corporations_boosts', 'Can access corporations boosts statistics'), ('corporations_tackle', 'Can access corporations tackle statistics'), ('corporations_snowflakes', 'Can access corporations snowflakes statistics'), ('corporations_caps', 'Can access corporations caps statistics'), ('corporations_fax', 'Can access corporations fax statistics'), ('corporations_supers', 'Can access corporations supers statistics'), ('corporations_titans', 'Can access corporations titans statistics'))},
        ),
    ]
