# Generated by Django 4.0.10 on 2023-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0008_corporationdata_rel_fats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationdata',
            name='rel_fats',
            field=models.FloatField(default=0),
        ),
    ]
