# Generated by Django 4.0.10 on 2023-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0009_alter_corporationdata_rel_fats'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationmains',
            name='corporation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corporationmains',
            name='fats',
            field=models.IntegerField(default=0),
        ),
    ]
