# Generated by Django 4.0.10 on 2023-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0010_corporationmains_corporation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporationmains',
            old_name='main_character',
            new_name='character_name',
        ),
        migrations.AddField(
            model_name='corporationmains',
            name='character_id',
            field=models.IntegerField(default=0),
        ),
    ]
