# Generated by Django 4.0.10 on 2023-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0011_rename_main_character_corporationmains_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationmains',
            name='corporation_name',
            field=models.CharField(max_length=255),
        ),
    ]
