# Generated by Django 4.0.10 on 2023-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0012_alter_corporationmains_corporation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationalts',
            name='main_character',
            field=models.CharField(max_length=255),
        ),
    ]
