# Generated by Django 4.0.10 on 2023-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0013_alter_corporationalts_main_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleersBoosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255, unique=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleersLogi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255, unique=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleersSnowflakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255, unique=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleersTackle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255, unique=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleersTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255, unique=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
            ],
        ),
    ]
