# Generated by Django 4.0.10 on 2023-05-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0016_capsuleersstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapsuleersStats',
            new_name='CapsuleersStat',
        ),
    ]
