# Generated by Django 4.0.10 on 2023-05-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0017_rename_capsuleersstats_capsuleersstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsuleersstat',
            name='stat',
            field=models.IntegerField(),
        ),
    ]
