# Generated by Django 4.0.10 on 2023-05-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0018_alter_capsuleersstat_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsuleersstat',
            name='stat',
        ),
    ]
