# Generated by Django 4.0.10 on 2023-05-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0019_remove_capsuleersstat_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuleersstat',
            name='identifier',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
