# Generated by Django 4.0.10 on 2023-05-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0020_capsuleersstat_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsuleersstat',
            old_name='identifier',
            new_name='stat',
        ),
    ]
