# Generated by Django 4.0.10 on 2023-05-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0021_rename_identifier_capsuleersstat_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuleersstat',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
    ]
