# Generated by Django 4.0.10 on 2023-05-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0022_capsuleersstat_identifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapsuleersBoosts',
        ),
        migrations.DeleteModel(
            name='CapsuleersCaps',
        ),
        migrations.DeleteModel(
            name='CapsuleersFAX',
        ),
        migrations.DeleteModel(
            name='CapsuleersLogi',
        ),
        migrations.DeleteModel(
            name='CapsuleersSnowflakes',
        ),
        migrations.DeleteModel(
            name='CapsuleersSupers',
        ),
        migrations.DeleteModel(
            name='CapsuleersTackle',
        ),
        migrations.DeleteModel(
            name='CapsuleersTitans',
        ),
        migrations.DeleteModel(
            name='CapsuleersTotal',
        ),
    ]
