# Generated by Django 4.0.10 on 2023-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0023_delete_capsuleersboosts_delete_capsuleerscaps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationalts',
            name='alt_id',
            field=models.IntegerField(default=0),
        ),
    ]
