# Generated by Django 4.0.10 on 2023-05-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0024_corporationalts_alt_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCharacters',
        ),
    ]
