# Generated by Django 4.0.10 on 2023-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatstats', '0025_delete_maincharacters'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationdata',
            name='shit_metric',
            field=models.FloatField(default=0),
        ),
    ]
